### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ppxasjsm** [jensengroup/procs15#1]
Hi,
I have been trying to install procs15. Installing Phaistos without it is no problem and works fine.
I am using this version of Phaistos:
https://sourceforge.net/projects/phaistos/

Then I untar everthing go to the module directory and run:
git clone git@github.com:jensengroup/procs15.git

Then I follow the build instructions of phaistos:

```
mkdir build
cd build
cmake ..
make -j 14
```

The build fails and I am not sure what to make of the output. Any ideas where I am going wrong?
And thanks for the help!
[build_fail.txt](https://github.com/jensengroup/procs15/files/202655/build_fail.txt)

**Comment by larsbratholm** [comment]
Since the Phaistos1.0 release, there's been some changes to the max size of a vector created with the vector_utils::make_vector class. And the number of options in procs exceeds that. The best way to fix this is to download a newer version of phaistos with 

svn checkout svn://svn.code.sf.net/p/phaistos/code/trunk phaistos

or alternatively edit the file procs15/bin/phaistos_cpp/global_option_definitions.cpp and uncomment lines 73 to 177. As there might be other changes made since the phaistos release, I would recommend trying to install the newer version.

**Comment by ppxasjsm** [comment]
Thanks for the comments! I'll try that. Maybe the readme could be updated with the correct dependency then, to avoid a confusion like that.

**Comment by larsbratholm** [comment]
Updated the readme. Thanks for finding that inconsistency.
